# Corso di Probabilità e Statistica - Vettori e Matrici
In questo capitolo introduciamo alcuni concetti elementari sulla generazione di vettori e matrici e numeri casuali. 

In [31]:
# importare packages
import numpy as np #operazioni numeriche

### Generare dati 

generare un numero random in [0,1]

In [39]:
x=np.random.rand()
x

0.009422152328312228

generare un numero random Gaussiano (media =0 varianza=1)

In [40]:
x=np.random.randn()
x

0.44099855860854126

In [ ]:
generare un numero random Gaussiano (media =m varianza=s)

In [43]:
m=1
s=2
x=s*np.random.randn()+m
x

-0.7339728891671453

generare i numeri tra a e b, spaziati di d

In [5]:
a=1
b=5
d=0.5
x = np.arange(a,b,d)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

generare N numeri equispaziati tra a e b (inclusi)

In [15]:
a=0
b=1
N=11
y = np.linspace(a,b,N)

In [16]:
y

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [24]:
#vettore di N componenti =0
N=3
zero_vector = np.zeros(N)
zero_vector

array([0., 0., 0.])

In [42]:
#vettore di N componenti random Gaussiane
N=3
random_vector = np.random.randn(N)
random_vector

array([ 1.25843411,  0.95108401, -2.31564976])

### Generare matrici 

In [22]:
#matrice NxM =0
N=3
M=4
zero_matrix = np.zeros( (N,M))
zero_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
#matrice NxM =1
N=3
M=4
one_matrix = np.ones( (N,M))
one_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
#matrice random NxM 
N=3
M=4
random_matrix=np.random.randn(N,M)
random_matrix

array([[ 0.13500398,  0.50946411,  0.1812327 , -0.86075953],
       [ 1.31353514, -0.39212944,  2.85435931, -0.49933899],
       [ 1.52922595,  0.18612959, -0.54598615, -1.34858678]])

Selezionare elementi di vettori o matrici

In [46]:
random_matrix[2,1]

0.18612959192046363

Selezionare colonna

In [47]:
random_matrix[:,1]

array([ 0.50946411, -0.39212944,  0.18612959])

Selezionare riga

In [49]:
random_matrix[2,:]

array([ 1.52922595,  0.18612959, -0.54598615, -1.34858678])

#### Esercizio

1) generare una matrice di dimensione 5x5 i cui elementi siano numeri random distribuiti tra [-1,1]

2) Selezionare la terza riga 