# Corso di Probabilità e Statistica 
## Vettori, matrici, numeri random
In questo capitolo introduciamo alcuni concetti elementari sulla generazione di vettori e matrici e numeri casuali. 

In [84]:
# importare packages
import numpy as np #operazioni numeriche


### Generare numeri random

generare un numero random in [0,1]

In [39]:
x_u=np.random.rand()
x_u

0.009422152328312228

generare un numero random Gaussiano (media =0 varianza=1)

In [40]:
x_g=np.random.randn()
x_g

0.44099855860854126

generare un numero random Gaussiano (media =m varianza=s)

In [43]:
m=1
s=2
x_g=s*np.random.randn()+m
x_g

-0.7339728891671453

Generare numero random con distribuzione esponenziale

In [89]:
x=np.random.rand() #numero random uniforme
r0=2
y_e=-np.log(1-x)/r0
y_e

0.024328426979297692

### Generare vettori

generare i numeri tra a e b, spaziati di d

In [5]:
a=1
b=5
d=0.5
x = np.arange(a,b,d)

generare N numeri equispaziati tra a e b (inclusi)

In [15]:
a=0
b=1
N=11
y = np.linspace(a,b,N)

In [16]:
y

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [24]:
#vettore di N componenti =0
N=3
zero_vector = np.zeros(N)
zero_vector

array([0., 0., 0.])

In [42]:
#vettore di N componenti random Gaussiane
N=3
random_vector = np.random.randn(N)
random_vector

array([ 1.25843411,  0.95108401, -2.31564976])

### Generare matrici 

In [22]:
#matrice NxM =0
N=3
M=4
zero_matrix = np.zeros( (N,M))
zero_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
#matrice NxM =1
N=3
M=4
one_matrix = np.ones( (N,M))
one_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
#matrice random NxM 
N=3
M=4
random_matrix=np.random.randn(N,M)
random_matrix

array([[ 0.13500398,  0.50946411,  0.1812327 , -0.86075953],
       [ 1.31353514, -0.39212944,  2.85435931, -0.49933899],
       [ 1.52922595,  0.18612959, -0.54598615, -1.34858678]])

Selezionare elementi di vettori o matrici

In [46]:
random_matrix[2,1]

0.18612959192046363

Selezionare colonna

In [47]:
random_matrix[:,1]

array([ 0.50946411, -0.39212944,  0.18612959])

Selezionare riga

In [49]:
random_matrix[2,:]

array([ 1.52922595,  0.18612959, -0.54598615, -1.34858678])

#### Esercizio

1) generare una matrice di dimensione 5x5 i cui elementi siano numeri random distribuiti tra [-1,1]

2) Selezionare la terza riga 

## Analisi statistica

### distribuzione uniforme

In [60]:
x10=np.random.rand(10)
x100=np.random.rand(100)
x1000=np.random.rand(1000)

In [63]:
# media
mu10=np.mean(x10)
mu100=np.mean(x100)
mu1000=np.mean(x1000)

In [62]:
mu10,mu100,mu1000

(0.5064069645305056, 0.5385535510220656, 0.49757153405100496)

In [72]:
# mediana
m10=np.median(x10)
m100=np.median(x100)
m1000=np.median(x1000)

In [73]:
m10,m100,m1000

(0.5144865597774462, 0.592295264669674, 0.5074192218343715)

In [68]:
# deviazione standard
sigma10=np.std(x10)
sigma100=np.std(x100)
sigma1000=np.std(x1000)

In [67]:
sigma10,sigma100,sigma1000

(0.3578908840993192, 0.2827625271057719, 0.28764538884552254)

In [69]:
#varianza
sigma_2_10=np.var(x10)
sigma_2_100=np.var(x100)
sigma_2_1000=np.var(x1000)

In [70]:
sigma_2_10,sigma_2_100,sigma_2_1000

(0.12808588492139233, 0.07995464673524237, 0.08273986972409186)

In [79]:
# minimo e massimo
min10=np.amin(x10)
min100=np.amin(x100)
min1000=np.amin(x1000)
max10=np.amax(x10)
max100=np.amax(x100)
max1000=np.amax(x1000)

In [83]:
min10,min100,min1000,max10,max100,max1000


(0.04344616350500674,
 0.02362016511459275,
 0.0007301986218472001,
 0.9664688278884368,
 0.9997421897711556,
 0.9991115634304468)

### Distribuzione esponenziale

In [94]:
N=1000
x=np.random.rand(N) #numero random uniforme
r0=2
y=-np.log(1-x)/r0

In [95]:
m=np.mean(y)
var=np.var(y)
std=np.std(y)
m,var,std

(0.5028713770940673, 0.24339111650533948, 0.4933468521287427)

per una distribuzione esponenziale la media è uguale alla deviazione standard